### ISSUE TITLE
'expires' should be 'expire_at'

### ISSUE THREAD

**Issue by rodriguezsergio** [needle-cookbooks/chef-sensu-handler#1]
If I manually make a stash that expires after X amount of time, the result looks like this

curl http://localhost:4567/stashes

[{"path":"silence/check/host","content":{"description":"Manual stash creation","owner":"sergio","timestamp":1390436487,"expire_at":"2014-01-23T19:30:00-05:00"},"expire":-1}]

But the key used to `POST` is using 'expires' instead. I am still able to manually create the stash when I use 'expires', but it will instead read as 'expires: never'.

I'm also finding that during a chef run, I am not seeing my stash get created, but I'm not sure what would be the cause of that.

**Comment by cwjohnston** [comment]
I think 'expires_at' is a sensu-admin invention, I'm closing this as I think Sensu's native stash expiration (implemented in #3) directly handles this case.
